apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::227471957411:role/UdacityFlaskDeployCBKubectlRole
      username: system:node:{{EC2PrivateDNSName}}  
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::227471957411:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1UM671OHF5LFF
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-05-26T01:13:28Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2021-05-26T01:13:28Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1543"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 91be4a84-ae80-49b5-8bf9-eb7df94d30db
